[env:rp2040zero]
platform = https://github.com/maxgerhardt/platform-raspberrypi.git
board = pico
framework = arduino

lib_deps =
    bodmer/TFT_eSPI

build_flags =
    -D USER_SETUP_LOADED
    -D ST7789_DRIVER
    -D TFT_WIDTH=240
    -D TFT_HEIGHT=320

    -D TFT_MISO=4
    -D TFT_MOSI=3
    -D TFT_SCLK=2

    -D TFT_CS=5
    -D TFT_DC=6
    -D TFT_RST=7

    -D SPI_FREQUENCY=27000000first 